/**
 * An error thrown when generating a proof fails.
 */
export declare class ProvingError extends Error {
    readonly retry: boolean;
    static readonly NAME = "ProvingError";
    /**
     * Creates a new instance
     * @param message - The error message.
     * @param cause - The cause of the error.
     * @param retry - Whether the proof should be retried.
     */
    constructor(message: string, cause?: unknown, retry?: boolean);
}
//# sourceMappingURL=proving_error.d.ts.map